image:
  file: .gitpod.Dockerfile

tasks:
  - name: NPM install
    init: npm install
  - name: Docker Deamon
    command : sudo docker-up

github:
  prebuilds:
    # enable for the main/default branch (defaults to true)
    main: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - mhutchie.git-graph
    - mikestead.dotenv
    - donjayamanne.githistory
    - hediet.vscode-drawio
    - shd101wyy.markdown-preview-enhanced
    - timonwong.shellcheck
    - tabnine.tabnine-vscode
    - redhat.vscode-yaml
